### ISSUE TITLE
数据字典自动走缓存，但是新增字典和字典组不刷新缓存，redis缓存对应的key是什么？麻烦老哥解答一下

### ISSUE THREAD

**Issue by cyqqqqq** [Ouyangan/hunt-admin#4]

**Comment by Ouyangan** [comment]
会走哦
key: sysDataItem.getSysDataGroupId() + "-" + sysDataItem.getKeyName()
看下

    @Override
    public String selectDataItemByKey(String key, Long groupId) {
        String value = (String) redisTemplate.opsForValue().get(groupId + "-" + key);
        if (value == null) {
            log.debug("get groupId:{} key:{} value from DB", groupId, key);
            value = sysDataItemMapper.selectByKey(key, groupId);
            redisTemplate.opsForValue().set(groupId + "-" + key, value);
        }
        return value;
    }

**Comment by cyqqqqq** [comment]
sorry没描述清楚，应该是新增字典组以后，新增字典找不到新增的字典组，新增字典组这个列表的缓存不会刷新，这个字典组列表的缓存是怎么命名的？

**Comment by Ouyangan** [comment]
代码很简单 , 建议看下systemService代码
